[core]
debug = false
bind_addr = "[::1]:8422"
auth_method = "token"  # token, oidc
allow_ports = "50000-60000"

[http]
bind_addr = "[::1]:8423"
default_domain = "localtest.me:8423"
default_static = "/opt/rslocald/webroot"

[tokens]
bob = "rslocald_abc11"
alice = "rslocald_abc32"

#[oidc]
#issuer = ""
#audience = ""