name: build
on:
  push:
    branches:
      - develop
      - master
  pull_request:

jobs:
  build:
    name: Build for ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-latest
            target: x86_64-apple-darwin
            exe: rslocal
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            exe: rslocal
#          - os: windows-latest
#            target: x86_64-pc-windows-msvc
#            exe: rslocal.exe
    steps:
      - name: Check out code
        uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - uses: Swatinem/rust-cache@v1
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
      - name: Run tests
        run: cargo test --verbose
      - uses: actions/upload-artifact@v2
        with:
          name: rslocal-${{ matrix.target }}
          path: target/debug/${{ matrix.exe }}